# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  bioc-release
sudo: false
cache: packages

os:
  - osx

# Make sure xz is installed:
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install xz || ( brew update && brew install xz ); fi

